### ISSUE TITLE
Do the encryption part in addOwnership function of TransactionBuilder

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/libjs#100]
### Is your feature request related to a problem?

Actually the `addOwernship` function in the `TransactionBuilder` expect as input the encoded secret, and a list of object containing public key and encoded secret key.
This might be a bit tricky for developer to use it as they'll need to understand how to create these to encrypted data using aesEncrypt en ecEncrypt.

### Describe the solution you'd like

Maybe we could embed directly in the addOwnership function the encryption part, so the developer could just pass the clear secret and a list of authorized public key.

**Comment by samuelmanzanera** [comment]
Actually, the point of using directly the secret encrypted is to avoid disclosure of the secret during the transaction building, as the secret might have been generated elsewhere like in HSM or other secret place.

So, the developer would have to know how to encrypt or use any encrypted data to inject.
