### ISSUE TITLE
Add connect button in Transaction builder to support custom urls.

### ISSUE THREAD

**Issue by apoorv-2204** [archethic-foundation/libjs#103]
### Is your feature request related to a problem?

By default tx builder connects to  localhost:4000, changing the url does not reconnect. 

![image](https://user-images.githubusercontent.com/90304197/214832257-4c2a2b12-d141-4177-8034-a7965b89ec0f.png)

### Describe the solution you'd like

we can have a button , to reconnect.

**Comment by Rudy-Perrin** [comment]
No need for a button.
The endpoint URL is updated when the Node Endpoint field changes.
