### ISSUE TITLE
Fix the isomorphic build

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/libjs#106]
There is currently about the target building for the lib.
While it's working on node, for the web when we are using CommonJS or ES modules, the build imported is not right and causes some errors based on Node.js native dependencies.

We have to provide a way to create polyfill to be isomorphic in terms of package.
We can take inspiration of https://github.com/lquixada/cross-fetch, with this conf: https://github.com/lquixada/cross-fetch/blob/main/rollup.config.js

**Comment by bchamagne** [comment]
While we're on it, it would be good to gitignore the dist/ folder and build it in the CI before publishing to npm.
see https://github.com/archethic-foundation/libjs/pull/94#issuecomment-1439899764
