### ISSUE TITLE
"isHex is not a function" error

### ISSUE THREAD

**Issue by CorentinAT** [archethic-foundation/libjs#117]
### Describe the problem you discovered

When using the function getBalance() in /lib/api.js, error with isHex() test, the function is not found. Not imported ?

### Describe the solution you'd like

Import the function in api.js

import { isHex } from "./utils.js";

in my case, it works.

**Comment by samuelmanzanera** [comment]
Thanks for the contribution

**Comment by redDwarf03** [comment]
@CorentinAT Hello. regarding your participation in the Archethic bug bounty, is it possible to contact you by private message please?

**Comment by CorentinAT** [comment]
@redDwarf03 Hello, I sent you a private message on discord (cocosupersympa)
