### ISSUE TITLE
Support Keychain creation

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/libjs#12]
Add function to create keychain and to create access to this keychain 

This involves:
- [x] create a `accessKeychain` transaction and encrypt, as secret, the keychain tx address
- [x] create a `keychain` transaction and encrypt as a secret the wallet with the UCO seed provided and authorizes the `accessKeychain` public key to decrypt it
- [x] retrieve the keychain decrypt it

Specification: https://archethic-foundation.github.io/archethic-docs/build/clients/wallet-spec

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/libjs/12?planning-poker) with ZenHub @apoorv-2204 @imnik11 @nilesh-uniris @roychowdhuryrohit-dev @samuel-uniris
