### ISSUE TITLE
[Bug]: Secret Ownership with multiple public keys not working using transactionBuilder.html

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/libjs#20]
### What happened?

Assuming https://github.com/archethic-foundation/archethic-node/issues/177 is fixed, using the [example/transactionBuilder.html](https://github.com/archethic-foundation/libjs/blob/88048f693d6c525fa1372f53c33cc659bf608792/example/transactionBuilder.html) when I try to pass multiple public keys in ownership, I get the following error.

<img width="1425" alt="Screenshot 2022-01-14 at 23 48 42" src="https://user-images.githubusercontent.com/24897721/149565455-b337da3f-2139-4915-9b7d-d3a6f2e0d9c1.png">

GraphQL request payload

<img width="1007" alt="Screenshot 2022-01-14 at 21 54 35" src="https://user-images.githubusercontent.com/24897721/149565552-78bc09f3-853b-4292-a637-1316fc49d5a9.png">

On logging the variable `authorizedKeys` in `previousSignaturePayload()`

https://github.com/archethic-foundation/libjs/blob/88048f693d6c525fa1372f53c33cc659bf608792/lib/transaction_builder.js#L329-L334

Console output

<img width="1248" alt="Screenshot 2022-01-14 at 23 53 11" src="https://user-images.githubusercontent.com/24897721/149566210-91690940-4bbf-4ce2-9d2a-3c85d22240f7.png">

### What is expected ?

Should get **200 OK** response and transaction should appear in ArchEthic explorer as well in GraphQL workspace.

This issue doesn't occur when single public key is sent.

**Comment by redDwarf03** [comment]
Same things in dart SDK
this issue becomes blocking
