### ISSUE TITLE
onAccountChange instead of onCurrentAccountChange

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/libjs#205]
### Describe the problem you discovered

On the readme, it is indicated that the function to use to received events about Account changes is  'onAccountChange' but it seems that it is 'onCurrentAccountChange'

### Describe the solution you'd like

Have the right term

**Comment by samuelmanzanera** [comment]
Thank you for the notice.
Indeed it seems to be `onCurrentAccountChange`

@Chralu could you confirm ?

**Comment by Chralu** [comment]
Yes, I confirm that issue. 
Thanks for your help 🙏

Fix is coming soon.
