### ISSUE TITLE
[Feature]: Addition of Setter Functions

### ISSUE THREAD

**Issue by prix-uniris** [archethic-foundation/libjs#22]
### Problem to solve

For Ledger Devices, It is needed to set the Previous Publick key and Previous Signature from the APDU response it gets after signing the transaction. 

The nextAddress also needs to be derived from the ledger device and set manually on transaction builder, Hence the need for a manual setter function.

### Solution

Requirement is two setter functions:
Ist to set previous_signature and previous_publickey
IInd to set next_address manually aka the `address` in the Transaction builder.

Here's code which I used while integrating ALCA (Archethic Ledger CLI Application):
/**
   * Set the transaction with Previous Publickey and Previous Signature
   * @param {String} 
   * @param {String}
   */
  setPreviousSignatureAndPreviousPublicKey(prevSign, prevPubKey) {
    if (typeof(prevSign) == "string") {
      if (!isHex(prevSign)) {
        throw "'previous Signature' must be in hexadecimal form if it's string"
      }
    }
    if (typeof(prevPubKey) == "string") {
      if (!isHex(prevPubKey)) {
        throw "'previous Public Key' must be in hexadecimal form if it's string"
      }
    }
    
    this.previousPublicKey = hexToUint8Array(prevPubKey);
    this.previousSignature = hexToUint8Array(prevSign);
    return this
  }

  setAddress(addr) {
    if (typeof(addr) !== "string" && !(addr instanceof Uint8Array)) {
      throw "'addr' must be a string or Uint8Array"
    }

    if (typeof(addr) == "string") {
      if (!isHex(addr)) {
        throw "'addr' must be in hexadecimal form if it's string"
      }
      addr = hexToUint8Array(addr)
    }
    this.address = addr;
    return this
  }

**Comment by samuel-uniris** [comment]
Yes no problem for this one.
It will come handy for furthermore integration wit Hardware.
You can make a PR for this one 🙂
