### ISSUE TITLE
Default parameter value is missing for txBuilder.build(seed, parseInt(index))

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/libjs#3]
### Here txBuilder.build() is called without passing the two parameters : curve, hashAlgo.
https://github.com/UNIRIS/uniris-libjs/blob/5f733654a1a904c10a89fd36782b438d543c76b3/example/transactionBuilder.html#L149

### But in the definition of TransactionBuilder.build, the required default parameter values for curve and hashAlgo is not defined.
https://github.com/UNIRIS/uniris-libjs/blob/5f733654a1a904c10a89fd36782b438d543c76b3/lib/transaction_builder.js#L224

How is this working? Am I missing anything?

**Comment by samuel-uniris** [comment]
Hi.

`build` leverages the `Crypto.deriveKeypair` function which handle the default case of the curve, but it can be addition to add the curve and hash algo to the build function.
