### ISSUE TITLE
[Question] - Curve by default

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/libjs#31]
### What happened?

Why in https://github.com/archethic-foundation/libjs/blob/8b7fea4b54778cce4967524ae10190fdb5e9a01f/lib/crypto.js#L23 the curve by default is « ed25519 » and https://github.com/archethic-foundation/libjs/blob/8b7fea4b54778cce4967524ae10190fdb5e9a01f/lib/crypto.js#L120 the curve by default is « P256 »

Just for info:
- the comment https://github.com/archethic-foundation/libjs/blob/8b7fea4b54778cce4967524ae10190fdb5e9a01f/lib/crypto.js#L118 doesn’t contain « ed25519 » reference
- the comment is not finish https://github.com/archethic-foundation/libjs/blob/8b7fea4b54778cce4967524ae10190fdb5e9a01f/test/index.js#L34

**Comment by samuel-uniris** [comment]
Hello.
Thanks for the report.
This is an inconsistency. 
Before the ed25519 curve was disabled due to compatibility issue with some lib, but it has been resolved for quite some time.
This inconsistency is fixed by 1a3658cbd27373fbbc5600e9b1387f04e0b08af0
