### ISSUE TITLE
(IMPROVEMENT) Big Endian format can be preferred over Uint8Array(array).reverse()

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/libjs#4]
### The following lines of code :

https://github.com/UNIRIS/uniris-libjs/blob/5f733654a1a904c10a89fd36782b438d543c76b3/lib/utils.js#L78-L79

### has the same behaviour as using the big endian format instead.

```js
view.setFloat64(0, number, false) 
return new Uint8Array(array)
```

**Comment by samuel-uniris** [comment]
Thanks. A PR would be good

**Comment by apoorv-2204** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/libjs/4?planning-poker) with ZenHub @roychowdhuryrohit-dev

**Comment by samuel-uniris** [comment]
> Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/libjs/4?planning-poker) with ZenHub @roychowdhuryrohit-dev

We have to check #43 first, if this issue is still valid ?

**Comment by roychowdhuryrohit-dev** [comment]
As far as I remember this fix was mostly for improving code aesthetics and doesn't break or change any functionality.
