### ISSUE TITLE
Add transaction building from the keychain

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/libjs#40]
### Problem to solve

Currently, when we are building a transaction, we are passing the seed and the index in the `TransactionBuilder.build` function.
However, with the keychain with can't leverage this function, so for this reason and hardware reason a function have been implemented to set the signature and public key of the transaction and not using the `build` function.
So we can still use the `setPreviousSignatureAndPreviousPublicKey` and using `keychain.deriveKeypair` to  leverage the tx builder and using the `Crypto.sign` function.
But this is not really easy or friendly, as it implies multiple steps.
So we should provide a better API to build transaction from the keychain services.

### Solution

The idea of the proposal would be to add a function in the keychain to build a transaction from a `TransactionBuilder` instance and abstract all those functions calls into a single one.

For example, we may have a function like: `keychain.buildTransaction(txBuilder, service, index)` where we are passing the builder as argument as well the service and the index of the keys to generate. Then the keys and signature will be generated and pass to the builder through the functions listed above. 
This way from a keychain's perspective it makes transaction building easier for devs and users of the lib.

**Comment by AmodD** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/libjs/40?planning-poker) with ZenHub @Neylix @samuel-uniris @apoorv-2204 @blackode
