### ISSUE TITLE
Add keychain transaction creation test

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/libjs#42]
### Solution

could you please add some tests to test these methods: 
- newAccessKeychainTransaction
- newKeychainTransaction
- getKeychain
these methods are here: https://github.com/archethic-foundation/libjs/blob/1e5e822788bf6c331c5b61a8c05da5801f5c9262/index.js#L176

**Comment by samuel-uniris** [comment]
Yes good idea. 

For the transaction creation no problem.

For the access this might be more tricky , we would have to mock API calls or refactor code to make more functional programming like by composing other pure and deterministic function.
