### ISSUE TITLE
Implement possibility to Add / Remove authorized public key in the keychain

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/libjs#46]
### Problem to solve

Actually when creating a Keychain we have only one authorized public key which is allowed to decrypt the Keychain secret.
In order to add new accessing wallet (i.e. a Ledger) or remove a corrupted / stolen key, we should implement function to add or remove authorized public key.

### Solution

We could create a new function in index.js:
`newKeychainUpdateTransaction(keychain, authorizedPublicKeys, originPrivateKey)`
This function should get the last transaction index of the keychain chain (based on keychain seed), build a new transaction as done in the `newKeychainTransaction()` with a new random aes key
Some changes may also be done in `getKeychain()` as it actually get the keychain address on the keychain access transaction, but it should get the last transaction address of this chain.
To be easier for developer, we can provide a function for getting the last transaction address of a keychain `getLastKeychainAddress(seed, endpoint)` (this function would be used in `getKeychain()`)

So the way to update the authorizedKeys would be : 
- Get the last Keychain address (getLastKeychainAddress()`)
- Get the ownerships of this transaction (`getTransactionOwnerships()`)
- Update Ownerships as wanted
- Get the keychain (`getKeychain()`)
- Create new update transaction (`updateKeychainTransaction()`)
- Send this transaction

We may also add some control to prevent using these function with an empty array of authorizedKey

**Comment by samuel-uniris** [comment]
What do you think of `updateKeychainTransaction` where we pass the list of authorized keys and the new keychain data (encrypted or not -> to see) ?

**Comment by Neylix** [comment]
Yes that is just the naming of the function, `updateKeychainTransaction` is better.
Howerver I think that we cannot pass encrypted keychain because we have to use the keychain seed to update the transaction and so if the keychain is encrypted we cannot have the seed.

**Comment by samuel-uniris** [comment]
Sure but I was just thinking if an hardware client want to update the keychain , the host SDK should not have access to the plaintext wallet

**Comment by samuel-uniris** [comment]
We could create two function `updateKeychain and `updateRawKeychain`

**Comment by Neylix** [comment]
I think that for interaction with hardware wallet, we could create a new Issue because there is a lot of change to do.
i.e we have to provide a function to get the encrypted keychain_access to be decrypted by the hardware, and then a function to get the encrypted keychain, also the `newKeychainTransaction` and `newKeychainAccessTransaction` shoud be able to create a keychain from a hardware wallet.

I think we can create 2 classes like "softwareTransaction" and "hardwareTransaction", one would be use by software wallet with all the transaction signed by seed etc, and the other classes provide function to create transactions with all the data needed for a hardware wallet to sign it

**Comment by samuel-uniris** [comment]
In order to make `newKeychainTransaction` and `NewAcessKeychainTransaction hardware compatibke, we would need to remove the `.build(seed).originSign(originKey)` and return the builder instead of the generated tx. 

For the `getKeychain` we would need to return the encrypted wallet with encrypted secret key and let client manage or provide some callback/handler to delegate to other piece of code. 

The approach of multi transaction builder can be interesting as well being based on the origin. Need to see if the comments above can resolve it without too much trouble.

**Comment by Neylix** [comment]
We also need to provide an function `setOriginSignature` as hardware wallet will also orign sign the transaction.

**Comment by AmodD** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/libjs/46?planning-poker) with ZenHub @blackode @apoorv-2204 @Neylix @samuel-uniris
