### ISSUE TITLE
Add `setOriginSignature` to the transaction builder

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/libjs#47]
### Problem to solve

Hardware devices need to sign the transaction with one of the origin shared private key.
Right now, the origin signature function accepts a private key but for non-disclosure of the key, we have to let the device sign it and return back the digest.

### Solution

We should add a new function in the transaction builder to add the origin signature appended to the transaction.

**Comment by AmodD** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/libjs/47?planning-poker) with ZenHub @apoorv-2204 @blackode @Neylix @samuel-uniris

**Comment by apoorv-2204** [comment]
Task 

- [ ] yellow paper
- [ ] libjs documentation
- [ ] archethic docs
- [ ] write code
- [ ]
