### ISSUE TITLE
Cancellation of GraphQL subscription

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/libjs#67]
### Is your feature request related to a problem?

When a transaction is submitted, we can await the completion.
However, the connection is never closed, and consume unnecessary resources.

### Describe the solution you'd like

Currently, we are using: `withAbsintheSocket.observe` and through an observable we can cancel the websocket subscription

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/libjs/67?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by prix-uniris** [comment]
https://github.com/absinthe-graphql/absinthe-socket/tree/master/packages/socket#observe
