### ISSUE TITLE
Provide functions get oracle data

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/libjs#72]
### Is your feature request related to a problem?

The node is exposing a GraphQL api queries and subscriptions to get the last oracle data
The libjs should have a set of functions to leverage it.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/libjs/72?planning-poker) with Zenhub @apoorv-2204 @Neylix @prix-uniris @samuel-uniris
