### ISSUE TITLE
Add getBalance function

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/libjs#90]
Provide a function to call the GraphQL query to get the balance of an address

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/libjs/90?planning-poker) with Zenhub @samuelmanzanera @apoorv-2204 @bchamagne @netboz @Neylix @tenmoves
