### ISSUE TITLE
Add function to update a keychain

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/libjs#92]
### Is your feature request related to a problem?

Actually, once a keychain is created, we cannot update it. We should provide function add or remove services and update the keychain.

### Describe the solution you'd like

We can create 3 functions:
- `addService` which locally add a service with it's name, derivation path, curve and hash. The 3 last parameters may have default value
- `removeService` which locally remove a service by it's name
- `update` which create a new transaction with the actual services of the local keychain object. Attention, this new transaction should also update the DID content based on the new services, and also use the same authorized public key as the previous transaction.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/libjs/92?planning-poker) with Zenhub @samuelmanzanera @apoorv-2204 @bchamagne @netboz @Neylix @tenmoves
